### ISSUE TITLE
TODO:  Add second level slash command parameters handling

### ISSUE THREAD

**Issue by Sing-Li** [Sing-Li/apps.bbbmeet#3]
Add the processing logic for second level command parameters:

`/bbbmeet  join <more subcommands>`

`/bbbmeet list  video`

`/bbbmeet play weekly`

...  and so on.

**Comment by debdutdeb** [comment]
Taking this on :)

**Comment by Sing-Li** [comment]
Thanks!    Assigned :)

**Comment by Sing-Li** [comment]
a reminder to add back your PR ;-)   @debdutdeb
